package com.example.regularincomeandinstallmentsampling.util

const val TEXT_NONE = "NONE"
const val TEXT_EVERY_DAY = "EVERY DAY"
const val TEXT_EVERY_WEEK = "EVERY WEEK"
const val TEXT_EVERY_TWO_WEEKS = "EVERY TWO WEEKS"
const val TEXT_EVERY_FOUR_WEEKS = "EVERY FOUR WEEKS"
const val TEXT_EVERY_MONTH = "EVERY MONTH"
const val TEXT_THE_END_OF_THE_MONTH = "THE END OF THE MONTH"
const val TEXT_EVERY_TWO_MONTHS = "EVERY TWO MONTHS"
const val TEXT_EVERY_THREE_MONTHS = "EVERY THREE MONTHS"
const val TEXT_EVERY_FOUR_MONTHS = "EVERY FOUR MONTHS"
const val TEXT_EVERY_SIX_MONTHS = "EVERY SIX MONTHS"
const val TEXT_EVERY_YEAR = "EVERY YEAR"

const val FLAG_NONE = -1
const val FLAG_EVERY_DAY = 0
const val FLAG_EVERY_WEEK = 1
const val FLAG_EVERY_TWO_WEEKS = 2
const val FLAG_EVERY_FOUR_WEEKS = 3
const val FLAG_EVERY_MONTH = 4
const val FLAG_THE_END_OF_THE_MONTH = 5
const val FLAG_EVERY_TWO_MONTHS = 6
const val FLAG_EVERY_THREE_MONTHS = 7
const val FLAG_EVERY_FOUR_MONTHS = 8
const val FLAG_EVERY_SIX_MONTHS = 9
const val FLAG_EVERY_YEAR = 10

const val PLUS_TIME_EVERY_DAY = "0001"
const val PLUS_TIME_EVERY_WEEK = "0007"
const val PLUS_TIME_EVERY_TWO_WEEKS = "0014"
const val PLUS_TIME_EVERY_FOUR_WEEKS = "0028"
const val PLUS_TIME_EVERY_MONTH = "0100"
const val PLUS_TIME_THE_END_OF_THE_MONTH = TEXT_THE_END_OF_THE_MONTH
const val PLUS_TIME_EVERY_TWO_MONTHS = "0200"
const val PLUS_TIME_EVERY_THREE_MONTHS = "0300"
const val PLUS_TIME_EVERY_FOUR_MONTHS = "0400"
const val PLUS_TIME_EVERY_SIX_MONTHS = "0600"
const val PLUS_TIME_EVERY_YEAR = "1200"

const val TEXT_SHOW_PERIOD = "Show Period"

val REPEAT_ITEM_LIST = arrayOf(
    TEXT_EVERY_DAY,
    TEXT_EVERY_WEEK,
    TEXT_EVERY_TWO_WEEKS,
    TEXT_EVERY_FOUR_WEEKS,
    TEXT_EVERY_MONTH,
    TEXT_THE_END_OF_THE_MONTH,
    TEXT_EVERY_TWO_MONTHS,
    TEXT_EVERY_THREE_MONTHS,
    TEXT_EVERY_FOUR_MONTHS,
    TEXT_EVERY_SIX_MONTHS,
    TEXT_EVERY_YEAR
)

const val TEXT_REPEAT = "repeat"
const val TEXT_NAME = "name"
const val TEXT_AMOUNT = "amount"
const val TEXT_DATE = "date"
const val TEXT_PREV = "prev"
const val TEXT_TARGET = "target"
const val TEXT_INIT = "init"
const val DB_NAME = "db"